version: '3'
services:
  mock_vidm_connector:
    build: .
    ports: 
      - 127.0.0.1:8080:8080
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
